/**
 * @author UC Innovation
 * @date 4/19/2021
 * @description override for salutation changes
 */
global class asc_BIO_NameOverride extends ucinn_ascendv2.ascend_BIO_Name {
    /**
     * Override the ascend function
     * @param   params      Map of params passed to and from ascend functions
     * @return              N/A
     */
    global override void updateAllContacts(Map<String, Object> params) {
        
    }
}